included: # paths to include during linting. `--path` is ignored if present.
  - Common
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length:
  warning: 220
